import type { Metadata } from "next";
import { Space_Mono, Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import { GameProvider } from "@/context/GameContext";


const spaceMono = Space_Mono({
  weight: ['400', '700'],
  variable: "--font-space-mono",
});

const barlow = Barlow({
  weight: ['100','200','300','400','500','600', '700','800','900'],
  variable: "--font-barlow"
});

const barlowCondensed = Barlow_Condensed({
  weight: ['100','200','300','400','500','600', '700','800','900'],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceMono.variable} ${barlow.variable} ${barlowCondensed.variable} h-full antialiased`}
    >
      <body className="min-h-full w-full">
        <GameProvider>
              {children}
          </GameProvider>
      </body>
    </html>
  );
}
